#include "../lib/core/src/integers.cpp"
#include "../lib/core/src/math.cpp"
#include "../lib/core/src/os.cpp"
#include "../lib/core/src/print.cpp"
#include "../lib/core/src/char_ptr.cpp"
#include "../lib/core/src/rnd.cpp"
#include "../lib/core/src/time.cpp"
#include "../lib/core/src/rune.cpp"
#include "../lib/core/src/bits.cpp"
#include "ui/ui.cpp"

#include "../lib/core/src/core.h"
#include "../lib/core/src/types.h"
#include "ui/ui.h"